project_id = "tfryydlbhqqzrdplxbib"

[functions.ai-mentor]
verify_jwt = false

[functions.translate]
verify_jwt = false

[functions.explain-code]
verify_jwt = false

[functions.recognize-components]
verify_jwt = false

[functions.recommend-projects]
verify_jwt = false